### ISSUE TITLE
white text on grey background

### ISSUE THREAD

**Issue by murko69** [blyad2137/facebook-dark-mode-expanded#1]
![tom](https://github.com/blyad2137/facebook-dark-mode-expanded/assets/12071221/374451e6-6e48-4140-a37f-8c751ffcd6bc)

In the picture I have put my mouse over the date of the post making a pop-up baloon appear with the date and time of the post!
In this case the time and date can nearly not be read due to it being a light color on a light background.
Also, you can clearly read the caption of the image inside this baloon because it's somewhat transparent.

Not very readable. Where in CSS can this be changed?
I would like to edit both the transparent part of the 'baloon' but also the text inside to a clearer, darker one

**Comment by blyad2137** [comment]
I've didn't really updated the `facebook dark mode expanded` for a long time, so this is expected, well I've updated it for myself but really didn't pushed the updates since I wasn't happy with them + the lack of time.

Answering the question where you can change it in CSS, its not really that easy, since Facebook has its CSS written in JS so it looks like shit and changes over some time. You can check everything in `inspect element` but you need a few tricks for this exact popup to stay so you can get the `class id` for it to change it. Bullshit aside im going to push the most updated version rn, so people won't have to fix all the stuff themselfs, that's why I do the stuff I do. Sorry for any inconveniences.
